// Thailand provinces and districts data
// All 77 provinces with their districts (amphoe/khet)
// Names in both English and Thai

export const THAILAND_PROVINCES = [
  {
    en: 'Amnat Charoen', th: 'อำนาจเจริญ',
    districts: [
      { en: 'Mueang Amnat Charoen', th: 'เมืองอำนาจเจริญ' },
      { en: 'Chanuman', th: 'ชานุมาน' },
      { en: 'Pathum Ratchawongsa', th: 'ปทุมราชวงศา' },
      { en: 'Phana', th: 'พนา' },
      { en: 'Senangkhanikhom', th: 'เสนางคนิคม' },
      { en: 'Hua Taphan', th: 'หัวตะพาน' },
      { en: 'Lue Amnat', th: 'ลืออำนาจ' },
    ]
  },
  {
    en: 'Ang Thong', th: 'อ่างทอง',
    districts: [
      { en: 'Mueang Ang Thong', th: 'เมืองอ่างทอง' },
      { en: 'Chaiyo', th: 'ไชโย' },
      { en: 'Pa Mok', th: 'ป่าโมก' },
      { en: 'Pho Thong', th: 'โพธิ์ทอง' },
      { en: 'Sawaeng Ha', th: 'แสวงหา' },
      { en: 'Wiset Chai Chan', th: 'วิเศษชัยชาญ' },
      { en: 'Samko', th: 'สามโก้' },
    ]
  },
  {
    en: 'Bangkok', th: 'กรุงเทพมหานคร',
    districts: [
      { en: 'Phra Nakhon', th: 'พระนคร' },
      { en: 'Dusit', th: 'ดุสิต' },
      { en: 'Nong Chok', th: 'หนองจอก' },
      { en: 'Bang Rak', th: 'บางรัก' },
      { en: 'Bang Khen', th: 'บางเขน' },
      { en: 'Bang Kapi', th: 'บางกะปิ' },
      { en: 'Pathum Wan', th: 'ปทุมวัน' },
      { en: 'Pom Prap Sattru Phai', th: 'ป้อมปราบศัตรูพ่าย' },
      { en: 'Phra Khanong', th: 'พระโขนง' },
      { en: 'Min Buri', th: 'มีนบุรี' },
      { en: 'Lat Krabang', th: 'ลาดกระบัง' },
      { en: 'Yan Nawa', th: 'ยานนาวา' },
      { en: 'Samphanthawong', th: 'สัมพันธวงศ์' },
      { en: 'Phaya Thai', th: 'พญาไท' },
      { en: 'Thon Buri', th: 'ธนบุรี' },
      { en: 'Bangkok Yai', th: 'บางกอกใหญ่' },
      { en: 'Huai Khwang', th: 'ห้วยขวาง' },
      { en: 'Khlong San', th: 'คลองสาน' },
      { en: 'Taling Chan', th: 'ตลิ่งชัน' },
      { en: 'Bangkok Noi', th: 'บางกอกน้อย' },
      { en: 'Bang Khun Thian', th: 'บางขุนเทียน' },
      { en: 'Phasi Charoen', th: 'ภาษีเจริญ' },
      { en: 'Nong Khaem', th: 'หนองแขม' },
      { en: 'Rat Burana', th: 'ราษฎร์บูรณะ' },
      { en: 'Bang Phlat', th: 'บางพลัด' },
      { en: 'Din Daeng', th: 'ดินแดง' },
      { en: 'Bueng Kum', th: 'บึงกุ่ม' },
      { en: 'Sathon', th: 'สาทร' },
      { en: 'Bang Sue', th: 'บางซื่อ' },
      { en: 'Chatuchak', th: 'จตุจักร' },
      { en: 'Bang Kho Laem', th: 'บางคอแหลม' },
      { en: 'Prawet', th: 'ประเวศ' },
      { en: 'Khlong Toei', th: 'คลองเตย' },
      { en: 'Suan Luang', th: 'สวนหลวง' },
      { en: 'Chom Thong', th: 'จอมทอง' },
      { en: 'Don Mueang', th: 'ดอนเมือง' },
      { en: 'Ratchathewi', th: 'ราชเทวี' },
      { en: 'Lat Phrao', th: 'ลาดพร้าว' },
      { en: 'Watthana', th: 'วัฒนา' },
      { en: 'Bang Khae', th: 'บางแค' },
      { en: 'Lak Si', th: 'หลักสี่' },
      { en: 'Sai Mai', th: 'สายไหม' },
      { en: 'Khan Na Yao', th: 'คันนายาว' },
      { en: 'Saphan Sung', th: 'สะพานสูง' },
      { en: 'Wang Thonglang', th: 'วังทองหลาง' },
      { en: 'Khlong Sam Wa', th: 'คลองสามวา' },
      { en: 'Bang Na', th: 'บางนา' },
      { en: 'Thawi Watthana', th: 'ทวีวัฒนา' },
      { en: 'Thung Khru', th: 'ทุ่งครุ' },
      { en: 'Bang Bon', th: 'บางบอน' },
    ]
  },
  {
    en: 'Bueng Kan', th: 'บึงกาฬ',
    districts: [
      { en: 'Mueang Bueng Kan', th: 'เมืองบึงกาฬ' },
      { en: 'Phon Charoen', th: 'พรเจริญ' },
      { en: 'So Phisai', th: 'โซ่พิสัย' },
      { en: 'Seka', th: 'เซกา' },
      { en: 'Pak Khat', th: 'ปากคาด' },
      { en: 'Bueng Khong Long', th: 'บึงโขงหลง' },
      { en: 'Si Wilai', th: 'ศรีวิไล' },
      { en: 'Bung Khla', th: 'บุ่งคล้า' },
    ]
  },
  {
    en: 'Buri Ram', th: 'บุรีรัมย์',
    districts: [
      { en: 'Mueang Buri Ram', th: 'เมืองบุรีรัมย์' },
      { en: 'Khu Mueang', th: 'คูเมือง' },
      { en: 'Krasang', th: 'กระสัง' },
      { en: 'Nang Rong', th: 'นางรอง' },
      { en: 'Non Suwan', th: 'หนองสุวรรณ' },
      { en: 'Lahan Sai', th: 'ละหานทราย' },
      { en: 'Prakhon Chai', th: 'ประโคนชัย' },
      { en: 'Ban Kruat', th: 'บ้านกรวด' },
      { en: 'Phutthaisong', th: 'พุทไธสง' },
      { en: 'Lam Plai Mat', th: 'ลำปลายมาศ' },
      { en: 'Satuek', th: 'สตึก' },
      { en: 'Pakham', th: 'ปะคำ' },
      { en: 'Na Pho', th: 'นาโพธิ์' },
      { en: 'Non Din Daeng', th: 'หนองหงส์' },
      { en: 'Phlapphla Chai', th: 'พลับพลาชัย' },
      { en: 'Huai Rat', th: 'ห้วยราช' },
      { en: 'Non Hong', th: 'หนองหงส์' },
      { en: 'Chamni', th: 'ชำนิ' },
      { en: 'Ban Mai Chaiyaphot', th: 'บ้านใหม่ไชยพจน์' },
      { en: 'Khaen Dong', th: 'แคนดง' },
      { en: 'Ban Dan', th: 'บ้านด่าน' },
      { en: 'Chaloem Phra Kiat', th: 'เฉลิมพระเกียรติ' },
    ]
  },
  {
    en: 'Chachoengsao', th: 'ฉะเชิงเทรา',
    districts: [
      { en: 'Mueang Chachoengsao', th: 'เมืองฉะเชิงเทรา' },
      { en: 'Bang Khla', th: 'บางคล้า' },
      { en: 'Bang Nam Priao', th: 'บางน้ำเปรี้ยว' },
      { en: 'Bang Pakong', th: 'บางปะกง' },
      { en: 'Ban Pho', th: 'บ้านโพธิ์' },
      { en: 'Phanom Sarakham', th: 'พนมสารคาม' },
      { en: 'Ratchasan', th: 'ราชสาส์น' },
      { en: 'Sanam Chai Khet', th: 'สนามชัยเขต' },
      { en: 'Plaeng Yao', th: 'แปลงยาว' },
      { en: 'Tha Takiap', th: 'ท่าตะเกียบ' },
      { en: 'Khlong Khuean', th: 'คลองเขื่อน' },
    ]
  },
  {
    en: 'Chai Nat', th: 'ชัยนาท',
    districts: [
      { en: 'Mueang Chai Nat', th: 'เมืองชัยนาท' },
      { en: 'Manorom', th: 'มโนรมย์' },
      { en: 'Wat Sing', th: 'วัดสิงห์' },
      { en: 'Sapphaya', th: 'สรรพยา' },
      { en: 'Sankhaburi', th: 'สรรคบุรี' },
      { en: 'Hankha', th: 'หันคา' },
      { en: 'Noen Kham', th: 'เนินขาม' },
      { en: 'Nong Mamong', th: 'หนองมะโมง' },
    ]
  },
  {
    en: 'Chaiyaphum', th: 'ชัยภูมิ',
    districts: [
      { en: 'Mueang Chaiyaphum', th: 'เมืองชัยภูมิ' },
      { en: 'Ban Khwao', th: 'บ้านเขว้า' },
      { en: 'Khon Sawan', th: 'คอนสวรรค์' },
      { en: 'Kaset Sombun', th: 'เกษตรสมบูรณ์' },
      { en: 'Non Sila', th: 'หนองบัวแดง' },
      { en: 'Chatturat', th: 'จัตุรัส' },
      { en: 'Bamnet Narong', th: 'บำเหน็จณรงค์' },
      { en: 'Nong Bua Daeng', th: 'หนองบัวแดง' },
      { en: 'Thep Sathit', th: 'เทพสถิต' },
      { en: 'Phu Khiao', th: 'ภูเขียว' },
      { en: 'Ban Thaen', th: 'บ้านแท่น' },
      { en: 'Kaeng Khro', th: 'แก้งคร้อ' },
      { en: 'Khon San', th: 'คอนสาร' },
      { en: 'Phakdi Chumphon', th: 'ภักดีชุมพล' },
      { en: 'Noen Sa-nga', th: 'เนินสง่า' },
      { en: 'Sap Yai', th: 'ซับใหญ่' },
    ]
  },
  {
    en: 'Chanthaburi', th: 'จันทบุรี',
    districts: [
      { en: 'Mueang Chanthaburi', th: 'เมืองจันทบุรี' },
      { en: 'Khlung', th: 'ขลุง' },
      { en: 'Tha Mai', th: 'ท่าใหม่' },
      { en: 'Pong Nam Ron', th: 'โป่งน้ำร้อน' },
      { en: 'Makham', th: 'มะขาม' },
      { en: 'Laem Sing', th: 'แหลมสิงห์' },
      { en: 'Soi Dao', th: 'สอยดาว' },
      { en: 'Kaeng Hang Maeo', th: 'แก่งหางแมว' },
      { en: 'Na Yai Am', th: 'นายายอาม' },
      { en: 'Khao Khitchakut', th: 'เขาคิชฌกูฏ' },
    ]
  },
  {
    en: 'Chiang Mai', th: 'เชียงใหม่',
    districts: [
      { en: 'Mueang Chiang Mai', th: 'เมืองเชียงใหม่' },
      { en: 'Chom Thong', th: 'จอมทอง' },
      { en: 'Mae Chaem', th: 'แม่แจ่ม' },
      { en: 'Chiang Dao', th: 'เชียงดาว' },
      { en: 'Doi Saket', th: 'ดอยสะเก็ด' },
      { en: 'Mae Taeng', th: 'แม่แตง' },
      { en: 'Mae Rim', th: 'แม่ริม' },
      { en: 'Samoeng', th: 'สะเมิง' },
      { en: 'Fang', th: 'ฝาง' },
      { en: 'Mae Ai', th: 'แม่อาย' },
      { en: 'Phrao', th: 'พร้าว' },
      { en: 'San Pa Tong', th: 'สันป่าตอง' },
      { en: 'San Kamphaeng', th: 'สันกำแพง' },
      { en: 'San Sai', th: 'สันทราย' },
      { en: 'Hang Dong', th: 'หางดง' },
      { en: 'Hot', th: 'ฮอด' },
      { en: 'Doi Tao', th: 'ดอยเต่า' },
      { en: 'Omkoi', th: 'อมก๋อย' },
      { en: 'Saraphi', th: 'สารภี' },
      { en: 'Wiang Haeng', th: 'เวียงแหง' },
      { en: 'Chai Prakan', th: 'ไชยปราการ' },
      { en: 'Mae Wang', th: 'แม่วาง' },
      { en: 'Mae On', th: 'แม่ออน' },
      { en: 'Doi Lo', th: 'ดอยหล่อ' },
      { en: 'Galyani Vadhana', th: 'กัลยาณิวัฒนา' },
    ]
  },
  {
    en: 'Chiang Rai', th: 'เชียงราย',
    districts: [
      { en: 'Mueang Chiang Rai', th: 'เมืองเชียงราย' },
      { en: 'Wiang Chai', th: 'เวียงชัย' },
      { en: 'Chiang Khong', th: 'เชียงของ' },
      { en: 'Thoeng', th: 'เทิง' },
      { en: 'Phan', th: 'พาน' },
      { en: 'Pa Daet', th: 'ป่าแดด' },
      { en: 'Mae Chan', th: 'แม่จัน' },
      { en: 'Chiang Saen', th: 'เชียงแสน' },
      { en: 'Mae Sai', th: 'แม่สาย' },
      { en: 'Mae Suai', th: 'แม่สรวย' },
      { en: 'Wiang Pa Pao', th: 'เวียงป่าเป้า' },
      { en: 'Phaya Mengrai', th: 'พญาเม็งราย' },
      { en: 'Wiang Kaen', th: 'เวียงแก่น' },
      { en: 'Khun Tan', th: 'ขุนตาล' },
      { en: 'Mae Fa Luang', th: 'แม่ฟ้าหลวง' },
      { en: 'Mae Lao', th: 'แม่ลาว' },
      { en: 'Wiang Chiang Rung', th: 'เวียงเชียงรุ้ง' },
      { en: 'Doi Luang', th: 'ดอยหลวง' },
    ]
  },
  {
    en: 'Chon Buri', th: 'ชลบุรี',
    districts: [
      { en: 'Mueang Chon Buri', th: 'เมืองชลบุรี' },
      { en: 'Ban Bueng', th: 'บ้านบึง' },
      { en: 'Nong Yai', th: 'หนองใหญ่' },
      { en: 'Bang Lamung', th: 'บางละมุง' },
      { en: 'Phan Thong', th: 'พานทอง' },
      { en: 'Phanat Nikhom', th: 'พนัสนิคม' },
      { en: 'Si Racha', th: 'ศรีราชา' },
      { en: 'Ko Sichang', th: 'เกาะสีชัง' },
      { en: 'Sattahip', th: 'สัตหีบ' },
      { en: 'Bo Thong', th: 'บ่อทอง' },
      { en: 'Ko Chan', th: 'เกาะจันทร์' },
    ]
  },
  {
    en: 'Chumphon', th: 'ชุมพร',
    districts: [
      { en: 'Mueang Chumphon', th: 'เมืองชุมพร' },
      { en: 'Tha Sae', th: 'ท่าแซะ' },
      { en: 'Pathiu', th: 'ปะทิว' },
      { en: 'Lang Suan', th: 'หลังสวน' },
      { en: 'Lamae', th: 'ละแม' },
      { en: 'Phato', th: 'พะโต๊ะ' },
      { en: 'Sawi', th: 'สวี' },
      { en: 'Thung Tako', th: 'ทุ่งตะโก' },
    ]
  },
  {
    en: 'Kalasin', th: 'กาฬสินธุ์',
    districts: [
      { en: 'Mueang Kalasin', th: 'เมืองกาฬสินธุ์' },
      { en: 'Na Mon', th: 'นามน' },
      { en: 'Kamalasai', th: 'กมลาไสย' },
      { en: 'Rong Kham', th: 'ร่องคำ' },
      { en: 'Kuchinarai', th: 'กุฉินารายณ์' },
      { en: 'Khao Wong', th: 'เขาวง' },
      { en: 'Yang Talat', th: 'ยางตลาด' },
      { en: 'Huai Mek', th: 'ห้วยเม็ก' },
      { en: 'Sahat Sakhan', th: 'สหัสขันธ์' },
      { en: 'Kham Muang', th: 'คำม่วง' },
      { en: 'Tha Khantho', th: 'ท่าคันโท' },
      { en: 'Nong Kung Si', th: 'หนองกุงศรี' },
      { en: 'Sam Chai', th: 'สามชัย' },
      { en: 'Na Khu', th: 'นาคู' },
      { en: 'Don Chan', th: 'ดอนจาน' },
      { en: 'Khlong Chai', th: 'ฆ้องชัย' },
      { en: 'Huai Phueng', th: 'ห้วยผึ้ง' },
      { en: 'Somdet', th: 'สมเด็จ' },
    ]
  },
  {
    en: 'Kamphaeng Phet', th: 'กำแพงเพชร',
    districts: [
      { en: 'Mueang Kamphaeng Phet', th: 'เมืองกำแพงเพชร' },
      { en: 'Sai Ngam', th: 'ไทรงาม' },
      { en: 'Khlong Lan', th: 'คลองลาน' },
      { en: 'Khanu Woralaksaburi', th: 'ขาณุวรลักษบุรี' },
      { en: 'Khlong Khlung', th: 'คลองขลุง' },
      { en: 'Phran Kratai', th: 'พรานกระต่าย' },
      { en: 'Lan Krabue', th: 'ลานกระบือ' },
      { en: 'Sai Thong Watthana', th: 'ทรายทองวัฒนา' },
      { en: 'Pang Sila Thong', th: 'ปางศิลาทอง' },
      { en: 'Bueng Samakkhi', th: 'บึงสามัคคี' },
      { en: 'Kosamphi Nakhon', th: 'โกสัมพีนคร' },
    ]
  },
  {
    en: 'Kanchanaburi', th: 'กาญจนบุรี',
    districts: [
      { en: 'Mueang Kanchanaburi', th: 'เมืองกาญจนบุรี' },
      { en: 'Sai Yok', th: 'ไทรโยค' },
      { en: 'Bo Phloi', th: 'บ่อพลอย' },
      { en: 'Si Sawat', th: 'ศรีสวัสดิ์' },
      { en: 'Tha Maka', th: 'ท่ามะกา' },
      { en: 'Tha Muang', th: 'ท่าม่วง' },
      { en: 'Thong Pha Phum', th: 'ทองผาภูมิ' },
      { en: 'Sangkhla Buri', th: 'สังขละบุรี' },
      { en: 'Phanom Thuan', th: 'พนมทวน' },
      { en: 'Lao Khwan', th: 'เลาขวัญ' },
      { en: 'Dan Makham Tia', th: 'ด่านมะขามเตี้ย' },
      { en: 'Nong Prue', th: 'หนองปรือ' },
      { en: 'Huai Krachao', th: 'ห้วยกระเจา' },
    ]
  },
  {
    en: 'Khon Kaen', th: 'ขอนแก่น',
    districts: [
      { en: 'Mueang Khon Kaen', th: 'เมืองขอนแก่น' },
      { en: 'Ban Fang', th: 'บ้านฝาง' },
      { en: 'Phra Yuen', th: 'พระยืน' },
      { en: 'Nong Ruea', th: 'หนองเรือ' },
      { en: 'Chum Phae', th: 'ชุมแพ' },
      { en: 'Si Chomphu', th: 'สีชมพู' },
      { en: 'Nam Phong', th: 'น้ำพอง' },
      { en: 'Ubolratana', th: 'อุบลรัตน์' },
      { en: 'Kranuan', th: 'กระนวน' },
      { en: 'Ban Phai', th: 'บ้านไผ่' },
      { en: 'Pueai Noi', th: 'เปือยน้อย' },
      { en: 'Phon', th: 'พล' },
      { en: 'Waeng Yai', th: 'แวงใหญ่' },
      { en: 'Waeng Noi', th: 'แวงน้อย' },
      { en: 'Nong Song Hong', th: 'หนองสองห้อง' },
      { en: 'Phu Wiang', th: 'ภูเวียง' },
      { en: 'Mancha Khiri', th: 'มัญจาคีรี' },
      { en: 'Chonnabot', th: 'ชนบท' },
      { en: 'Khao Suan Kwang', th: 'เขาสวนกวาง' },
      { en: 'Phu Pha Man', th: 'ภูผาม่าน' },
      { en: 'Sam Sung', th: 'ซำสูง' },
      { en: 'Khok Pho Chai', th: 'โคกโพธิ์ไชย' },
      { en: 'Nong Na Kham', th: 'หนองนาคำ' },
      { en: 'Ban Haet', th: 'บ้านแฮด' },
      { en: 'Non Sila', th: 'โนนศิลา' },
      { en: 'Wiang Kao', th: 'เวียงเก่า' },
    ]
  },
  {
    en: 'Krabi', th: 'กระบี่',
    districts: [
      { en: 'Mueang Krabi', th: 'เมืองกระบี่' },
      { en: 'Khao Phanom', th: 'เขาพนม' },
      { en: 'Ko Lanta', th: 'เกาะลันตา' },
      { en: 'Khlong Thom', th: 'คลองท่อม' },
      { en: 'Ao Luek', th: 'อ่าวลึก' },
      { en: 'Plai Phraya', th: 'ปลายพระยา' },
      { en: 'Lam Thap', th: 'ลำทับ' },
      { en: 'Nuea Khlong', th: 'เหนือคลอง' },
    ]
  },
  {
    en: 'Lampang', th: 'ลำปาง',
    districts: [
      { en: 'Mueang Lampang', th: 'เมืองลำปาง' },
      { en: 'Mae Mo', th: 'แม่เมาะ' },
      { en: 'Ko Kha', th: 'เกาะคา' },
      { en: 'Soem Ngam', th: 'เสริมงาม' },
      { en: 'Ngao', th: 'งาว' },
      { en: 'Chae Hom', th: 'แจ้ห่ม' },
      { en: 'Wang Nuea', th: 'วังเหนือ' },
      { en: 'Thoen', th: 'เถิน' },
      { en: 'Mae Phrik', th: 'แม่พริก' },
      { en: 'Mae Tha', th: 'แม่ทะ' },
      { en: 'Sop Prap', th: 'สบปราบ' },
      { en: 'Hang Chat', th: 'ห้างฉัตร' },
      { en: 'Mueang Pan', th: 'เมืองปาน' },
    ]
  },
  {
    en: 'Lamphun', th: 'ลำพูน',
    districts: [
      { en: 'Mueang Lamphun', th: 'เมืองลำพูน' },
      { en: 'Mae Tha', th: 'แม่ทา' },
      { en: 'Ban Hong', th: 'บ้านโฮ่ง' },
      { en: 'Li', th: 'ลี้' },
      { en: 'Thung Hua Chang', th: 'ทุ่งหัวช้าง' },
      { en: 'Pa Sang', th: 'ป่าซาง' },
      { en: 'Ban Thi', th: 'บ้านธิ' },
      { en: 'Wiang Nong Long', th: 'เวียงหนองล่อง' },
    ]
  },
  {
    en: 'Loei', th: 'เลย',
    districts: [
      { en: 'Mueang Loei', th: 'เมืองเลย' },
      { en: 'Na Duang', th: 'นาด้วง' },
      { en: 'Chiang Khan', th: 'เชียงคาน' },
      { en: 'Pak Chom', th: 'ปากชม' },
      { en: 'Dan Sai', th: 'ด่านซ้าย' },
      { en: 'Na Haeo', th: 'นาแห้ว' },
      { en: 'Phu Ruea', th: 'ภูเรือ' },
      { en: 'Tha Li', th: 'ท่าลี่' },
      { en: 'Wang Saphung', th: 'วังสะพุง' },
      { en: 'Phu Kradueng', th: 'ภูกระดึง' },
      { en: 'Phu Luang', th: 'ภูหลวง' },
      { en: 'Pha Khao', th: 'ผาขาว' },
      { en: 'Erawan', th: 'เอราวัณ' },
      { en: 'Nong Hin', th: 'หนองหิน' },
    ]
  },
  {
    en: 'Lop Buri', th: 'ลพบุรี',
    districts: [
      { en: 'Mueang Lop Buri', th: 'เมืองลพบุรี' },
      { en: 'Phatthana Nikhom', th: 'พัฒนานิคม' },
      { en: 'Khok Samrong', th: 'โคกสำโรง' },
      { en: 'Chai Badan', th: 'ชัยบาดาล' },
      { en: 'Tha Wung', th: 'ท่าวุ้ง' },
      { en: 'Ban Mi', th: 'บ้านหมี่' },
      { en: 'Tha Luang', th: 'ท่าหลวง' },
      { en: 'Sa Bot', th: 'สระโบสถ์' },
      { en: 'Khok Charoen', th: 'โคกเจริญ' },
      { en: 'Lam Sonthi', th: 'ลำสนธิ' },
      { en: 'Nong Muang', th: 'หนองม่วง' },
    ]
  },
  {
    en: 'Mae Hong Son', th: 'แม่ฮ่องสอน',
    districts: [
      { en: 'Mueang Mae Hong Son', th: 'เมืองแม่ฮ่องสอน' },
      { en: 'Khun Yuam', th: 'ขุนยวม' },
      { en: 'Pai', th: 'ปาย' },
      { en: 'Mae Sariang', th: 'แม่สะเรียง' },
      { en: 'Mae La Noi', th: 'แม่ลาน้อย' },
      { en: 'Sop Moei', th: 'สบเมย' },
      { en: 'Pangmapha', th: 'ปางมะผ้า' },
    ]
  },
  {
    en: 'Maha Sarakham', th: 'มหาสารคาม',
    districts: [
      { en: 'Mueang Maha Sarakham', th: 'เมืองมหาสารคาม' },
      { en: 'Kae Dam', th: 'แกดำ' },
      { en: 'Kosum Phisai', th: 'โกสุมพิสัย' },
      { en: 'Kantharawichai', th: 'กันทรวิชัย' },
      { en: 'Chiang Yuen', th: 'เชียงยืน' },
      { en: 'Borabue', th: 'บรบือ' },
      { en: 'Na Chueak', th: 'นาเชือก' },
      { en: 'Phayakkhaphum Phisai', th: 'พยัคฆภูมิพิสัย' },
      { en: 'Wapi Pathum', th: 'วาปีปทุม' },
      { en: 'Na Dun', th: 'นาดูน' },
      { en: 'Yang Si Surat', th: 'ยางสีสุราช' },
      { en: 'Kut Rang', th: 'กุดรัง' },
      { en: 'Chuen Chom', th: 'ชื่นชม' },
    ]
  },
  {
    en: 'Mukdahan', th: 'มุกดาหาร',
    districts: [
      { en: 'Mueang Mukdahan', th: 'เมืองมุกดาหาร' },
      { en: 'Nikhom Kham Soi', th: 'นิคมคำสร้อย' },
      { en: 'Don Tan', th: 'ดอนตาล' },
      { en: 'Dong Luang', th: 'ดงหลวง' },
      { en: 'Khamcha-i', th: 'คำชะอี' },
      { en: 'Wan Yai', th: 'หว้านใหญ่' },
      { en: 'Nong Sung', th: 'หนองสูง' },
    ]
  },
  {
    en: 'Nakhon Nayok', th: 'นครนายก',
    districts: [
      { en: 'Mueang Nakhon Nayok', th: 'เมืองนครนายก' },
      { en: 'Ban Na', th: 'บ้านนา' },
      { en: 'Ongkharak', th: 'องครักษ์' },
      { en: 'Pak Phli', th: 'ปากพลี' },
    ]
  },
  {
    en: 'Nakhon Pathom', th: 'นครปฐม',
    districts: [
      { en: 'Mueang Nakhon Pathom', th: 'เมืองนครปฐม' },
      { en: 'Kamphaeng Saen', th: 'กำแพงแสน' },
      { en: 'Nakhon Chai Si', th: 'นครชัยศรี' },
      { en: 'Don Tum', th: 'ดอนตูม' },
      { en: 'Bang Len', th: 'บางเลน' },
      { en: 'Sam Phran', th: 'สามพราน' },
      { en: 'Phutthamonthon', th: 'พุทธมณฑล' },
    ]
  },
  {
    en: 'Nakhon Phanom', th: 'นครพนม',
    districts: [
      { en: 'Mueang Nakhon Phanom', th: 'เมืองนครพนม' },
      { en: 'Pla Pak', th: 'ปลาปาก' },
      { en: 'Tha Uthen', th: 'ท่าอุเทน' },
      { en: 'Ban Phaeng', th: 'บ้านแพง' },
      { en: 'That Phanom', th: 'ธาตุพนม' },
      { en: 'Renu Nakhon', th: 'เรณูนคร' },
      { en: 'Na Kae', th: 'นาแก' },
      { en: 'Sri Songkhram', th: 'ศรีสงคราม' },
      { en: 'Na Wa', th: 'นาหว้า' },
      { en: 'Phon Sawan', th: 'โพนสวรรค์' },
      { en: 'Na Thom', th: 'นาทม' },
      { en: 'Wang Yang', th: 'วังยาง' },
    ]
  },
  {
    en: 'Nakhon Ratchasima', th: 'นครราชสีมา',
    districts: [
      { en: 'Mueang Nakhon Ratchasima', th: 'เมืองนครราชสีมา' },
      { en: 'Khon Buri', th: 'ครบุรี' },
      { en: 'Soeng Sang', th: 'เสิงสาง' },
      { en: 'Kham Thale So', th: 'คำตาลัสอ' },
      { en: 'Dan Khun Thot', th: 'ด่านขุนทด' },
      { en: 'Chok Chai', th: 'โชคชัย' },
      { en: 'Pak Thong Chai', th: 'ปากช่อง' },
      { en: 'Non Sung', th: 'โนนสูง' },
      { en: 'Kham Sakaesaeng', th: 'ขามสะแกแสง' },
      { en: 'Bua Yai', th: 'บัวใหญ่' },
      { en: 'Prathai', th: 'ประทาย' },
      { en: 'Phu Wiang', th: 'ปักธงชัย' },
      { en: 'Phimai', th: 'พิมาย' },
      { en: 'Huai Thalaeng', th: 'ห้วยแถลง' },
      { en: 'Chakkarat', th: 'จักราช' },
      { en: 'Sung Noen', th: 'สูงเนิน' },
      { en: 'Kham Thale So', th: 'ขามทะเลสอ' },
      { en: 'Sikhiu', th: 'สีคิ้ว' },
      { en: 'Pak Chong', th: 'ปากช่อง' },
      { en: 'Non Thai', th: 'โนนไทย' },
      { en: 'Non Daeng', th: 'โนนแดง' },
      { en: 'Wang Nam Khiao', th: 'วังน้ำเขียว' },
      { en: 'Thepharak', th: 'เทพารักษ์' },
      { en: 'Mueang Yang', th: 'เมืองยาง' },
      { en: 'Phra Thong Kham', th: 'พระทองคำ' },
      { en: 'Lam Thamenchai', th: 'ลำทะเมนชัย' },
      { en: 'Bua Lai', th: 'บัวลาย' },
      { en: 'Sida', th: 'สีดา' },
      { en: 'Chaloem Phra Kiat', th: 'เฉลิมพระเกียรติ' },
    ]
  },
  {
    en: 'Nakhon Sawan', th: 'นครสวรรค์',
    districts: [
      { en: 'Mueang Nakhon Sawan', th: 'เมืองนครสวรรค์' },
      { en: 'Krok Phra', th: 'โกรกพระ' },
      { en: 'Chum Saeng', th: 'ชุมแสง' },
      { en: 'Nong Bua', th: 'หนองบัว' },
      { en: 'Banphot Phisai', th: 'บรรพตพิสัย' },
      { en: 'Kao Liao', th: 'เก้าเลี้ยว' },
      { en: 'Takhli', th: 'ตากฟ้า' },
      { en: 'Tha Tako', th: 'ท่าตะโก' },
      { en: 'Phaisali', th: 'ไพศาลี' },
      { en: 'Phayuha Khiri', th: 'พยุหะคีรี' },
      { en: 'Lat Yao', th: 'ลาดยาว' },
      { en: 'Tak Fa', th: 'ตากฟ้า' },
      { en: 'Mae Wong', th: 'แม่วงก์' },
      { en: 'Mae Poen', th: 'แม่เปิน' },
      { en: 'Chum Ta Bong', th: 'ชุมตาบง' },
    ]
  },
  {
    en: 'Nakhon Si Thammarat', th: 'นครศรีธรรมราช',
    districts: [
      { en: 'Mueang Nakhon Si Thammarat', th: 'เมืองนครศรีธรรมราช' },
      { en: 'Phrom Khiri', th: 'พรหมคีรี' },
      { en: 'Lan Saka', th: 'ลานสกา' },
      { en: 'Chawang', th: 'ฉวาง' },
      { en: 'Phipun', th: 'พิปูน' },
      { en: 'Chian Yai', th: 'เชียรใหญ่' },
      { en: 'Cha-uat', th: 'ชะอวด' },
      { en: 'Tha Sala', th: 'ท่าศาลา' },
      { en: 'Thung Song', th: 'ทุ่งสง' },
      { en: 'Na Bon', th: 'นาบอน' },
      { en: 'Thung Yai', th: 'ทุ่งใหญ่' },
      { en: 'Pak Phanang', th: 'ปากพนัง' },
      { en: 'Ron Phibun', th: 'ร่อนพิบูลย์' },
      { en: 'Sichon', th: 'สิชล' },
      { en: 'Khanom', th: 'ขนอม' },
      { en: 'Hua Sai', th: 'หัวไทร' },
      { en: 'Bang Khan', th: 'บางขัน' },
      { en: 'Tham Phannara', th: 'ถ้ำพรรณรา' },
      { en: 'Chulabhorn', th: 'จุฬาภรณ์' },
      { en: 'Phra Phrom', th: 'พระพรหม' },
      { en: 'Nopphitam', th: 'นบพิตำ' },
      { en: 'Chang Klang', th: 'ช้างกลาง' },
      { en: 'Chaloem Phra Kiat', th: 'เฉลิมพระเกียรติ' },
    ]
  },
  {
    en: 'Nan', th: 'น่าน',
    districts: [
      { en: 'Mueang Nan', th: 'เมืองน่าน' },
      { en: 'Mae Charim', th: 'แม่จริม' },
      { en: 'Ban Luang', th: 'บ้านหลวง' },
      { en: 'Na Noi', th: 'นาน้อย' },
      { en: 'Pua', th: 'ปัว' },
      { en: 'Tha Wang Pha', th: 'ท่าวังผา' },
      { en: 'Wiang Sa', th: 'เวียงสา' },
      { en: 'Thung Chang', th: 'ทุ่งช้าง' },
      { en: 'Chiang Klang', th: 'เชียงกลาง' },
      { en: 'Na Muen', th: 'นาหมื่น' },
      { en: 'Santi Suk', th: 'สันติสุข' },
      { en: 'Bo Kluea', th: 'บ่อเกลือ' },
      { en: 'Song Khwae', th: 'สองแคว' },
      { en: 'Phu Phiang', th: 'ภูเพียง' },
      { en: 'Chaloem Phra Kiat', th: 'เฉลิมพระเกียรติ' },
    ]
  },
  {
    en: 'Narathiwat', th: 'นราธิวาส',
    districts: [
      { en: 'Mueang Narathiwat', th: 'เมืองนราธิวาส' },
      { en: 'Tak Bai', th: 'ตากใบ' },
      { en: 'Bacho', th: 'บาเจาะ' },
      { en: 'Yi-ngo', th: 'ยี่งอ' },
      { en: 'Ra-ngae', th: 'ระแงะ' },
      { en: 'Rueso', th: 'รือเสาะ' },
      { en: 'Si Sakhon', th: 'ศรีสาคร' },
      { en: 'Waeng', th: 'แว้ง' },
      { en: 'Sukhirin', th: 'สุคิริน' },
      { en: 'Su-ngai Kolok', th: 'สุไหงโก-ลก' },
      { en: 'Su-ngai Padi', th: 'สุไหงปาดี' },
      { en: 'Chanae', th: 'จะแนะ' },
      { en: 'Cho Airong', th: 'เจาะไอร้อง' },
    ]
  },
  {
    en: 'Nong Bua Lam Phu', th: 'หนองบัวลำภู',
    districts: [
      { en: 'Mueang Nong Bua Lam Phu', th: 'เมืองหนองบัวลำภู' },
      { en: 'Na Klang', th: 'นากลาง' },
      { en: 'Non Sang', th: 'โนนสัง' },
      { en: 'Si Bun Rueang', th: 'ศรีบุญเรือง' },
      { en: 'Suwannakhuha', th: 'สุวรรณคูหา' },
      { en: 'Na Wang', th: 'นาวัง' },
    ]
  },
  {
    en: 'Nong Khai', th: 'หนองคาย',
    districts: [
      { en: 'Mueang Nong Khai', th: 'เมืองหนองคาย' },
      { en: 'Tha Bo', th: 'ท่าบ่อ' },
      { en: 'Phon Phisai', th: 'โพนพิสัย' },
      { en: 'Si Chiang Mai', th: 'ศรีเชียงใหม่' },
      { en: 'Sang Khom', th: 'สังคม' },
      { en: 'Sakhrai', th: 'สระใคร' },
      { en: 'Fao Rai', th: 'เฝ้าไร่' },
      { en: 'Rattanawapi', th: 'รัตนวาปี' },
      { en: 'Pho Tak', th: 'โพธิ์ตาก' },
    ]
  },
  {
    en: 'Nonthaburi', th: 'นนทบุรี',
    districts: [
      { en: 'Mueang Nonthaburi', th: 'เมืองนนทบุรี' },
      { en: 'Bang Kruai', th: 'บางกรวย' },
      { en: 'Bang Yai', th: 'บางใหญ่' },
      { en: 'Bang Bua Thong', th: 'บางบัวทอง' },
      { en: 'Sai Noi', th: 'ไทรน้อย' },
      { en: 'Pak Kret', th: 'ปากเกร็ด' },
    ]
  },
  {
    en: 'Pathum Thani', th: 'ปทุมธานี',
    districts: [
      { en: 'Mueang Pathum Thani', th: 'เมืองปทุมธานี' },
      { en: 'Khlong Luang', th: 'คลองหลวง' },
      { en: 'Thanyaburi', th: 'ธัญบุรี' },
      { en: 'Nong Suea', th: 'หนองเสือ' },
      { en: 'Lat Lum Kaeo', th: 'ลาดหลุมแก้ว' },
      { en: 'Lam Luk Ka', th: 'ลำลูกกา' },
      { en: 'Sam Khok', th: 'สามโคก' },
    ]
  },
  {
    en: 'Pattani', th: 'ปัตตานี',
    districts: [
      { en: 'Mueang Pattani', th: 'เมืองปัตตานี' },
      { en: 'Khok Pho', th: 'โคกโพธิ์' },
      { en: 'Nong Chik', th: 'หนองจิก' },
      { en: 'Panare', th: 'ปะนาเระ' },
      { en: 'Mayo', th: 'มายอ' },
      { en: 'Thung Yang Daeng', th: 'ทุ่งยางแดง' },
      { en: 'Sai Buri', th: 'สายบุรี' },
      { en: 'Mai Kaen', th: 'ไม้แก่น' },
      { en: 'Yaring', th: 'ยะหริ่ง' },
      { en: 'Yarang', th: 'ยะรัง' },
      { en: 'Kapho', th: 'กะพ้อ' },
      { en: 'Mae Lan', th: 'แม่ลาน' },
    ]
  },
  {
    en: 'Phang Nga', th: 'พังงา',
    districts: [
      { en: 'Mueang Phang Nga', th: 'เมืองพังงา' },
      { en: 'Ko Yao', th: 'เกาะยาว' },
      { en: 'Kapong', th: 'กะปง' },
      { en: 'Takua Thung', th: 'ตะกั่วทุ่ง' },
      { en: 'Takua Pa', th: 'ตะกั่วป่า' },
      { en: 'Khura Buri', th: 'คุระบุรี' },
      { en: 'Thap Put', th: 'ทับปุด' },
      { en: 'Thai Mueang', th: 'ท้ายเหมือง' },
    ]
  },
  {
    en: 'Phatthalung', th: 'พัทลุง',
    districts: [
      { en: 'Mueang Phatthalung', th: 'เมืองพัทลุง' },
      { en: 'Kong Ra', th: 'กงหรา' },
      { en: 'Khao Chaison', th: 'เขาชัยสน' },
      { en: 'Tamot', th: 'ตะโหมด' },
      { en: 'Khuan Khanun', th: 'ควนขนุน' },
      { en: 'Pak Phayun', th: 'ปากพะยูน' },
      { en: 'Si Banphot', th: 'ศรีบรรพต' },
      { en: 'Pa Bon', th: 'ป่าบอน' },
      { en: 'Bang Kaew', th: 'บางแก้ว' },
      { en: 'Pa Phayom', th: 'ป่าพะยอม' },
      { en: 'Sri Nakharin', th: 'ศรีนครินทร์' },
    ]
  },
  {
    en: 'Phayao', th: 'พะเยา',
    districts: [
      { en: 'Mueang Phayao', th: 'เมืองพะเยา' },
      { en: 'Chun', th: 'จุน' },
      { en: 'Chiang Kham', th: 'เชียงคำ' },
      { en: 'Chiang Muan', th: 'เชียงม่วน' },
      { en: 'Dok Khamtai', th: 'ดอกคำใต้' },
      { en: 'Pong', th: 'ปง' },
      { en: 'Mae Chai', th: 'แม่ใจ' },
      { en: 'Phu Sang', th: 'ภูซาง' },
      { en: 'Phu Kamyao', th: 'ภูกามยาว' },
    ]
  },
  {
    en: 'Phetchabun', th: 'เพชรบูรณ์',
    districts: [
      { en: 'Mueang Phetchabun', th: 'เมืองเพชรบูรณ์' },
      { en: 'Chon Daen', th: 'ชนแดน' },
      { en: 'Lom Sak', th: 'หล่มสัก' },
      { en: 'Lom Kao', th: 'หล่มเก่า' },
      { en: 'Wichian Buri', th: 'วิเชียรบุรี' },
      { en: 'Si Thep', th: 'ศรีเทพ' },
      { en: 'Nong Phai', th: 'หนองไผ่' },
      { en: 'Bueng Sam Phan', th: 'บึงสามพัน' },
      { en: 'Nam Nao', th: 'น้ำหนาว' },
      { en: 'Wang Phrong', th: 'วังโป่ง' },
      { en: 'Khao Kho', th: 'เขาค้อ' },
    ]
  },
  {
    en: 'Phetchaburi', th: 'เพชรบุรี',
    districts: [
      { en: 'Mueang Phetchaburi', th: 'เมืองเพชรบุรี' },
      { en: 'Khao Yoi', th: 'เขาย้อย' },
      { en: 'Nong Ya Plong', th: 'หนองหญ้าปล้อง' },
      { en: 'Cha-am', th: 'ชะอำ' },
      { en: 'Tha Yang', th: 'ท่ายาง' },
      { en: 'Ban Lat', th: 'บ้านลาด' },
      { en: 'Ban Laem', th: 'บ้านแหลม' },
      { en: 'Kaeng Krachan', th: 'แก่งกระจาน' },
    ]
  },
  {
    en: 'Phichit', th: 'พิจิตร',
    districts: [
      { en: 'Mueang Phichit', th: 'เมืองพิจิตร' },
      { en: 'Wang Sai Phun', th: 'วังทรายพูน' },
      { en: 'Pho Prathap Chang', th: 'โพธิ์ประทับช้าง' },
      { en: 'Taphan Hin', th: 'ตะพานหิน' },
      { en: 'Bang Mun Nak', th: 'บางมูลนาก' },
      { en: 'Pho Thale', th: 'โพทะเล' },
      { en: 'Sam Ngam', th: 'สามง่าม' },
      { en: 'Thap Khlo', th: 'ทับคล้อ' },
      { en: 'Sak Lek', th: 'สากเหล็ก' },
      { en: 'Bueng Na Rang', th: 'บึงนาราง' },
      { en: 'Dong Charoen', th: 'ดงเจริญ' },
      { en: 'Wachirabarami', th: 'วชิรบารมี' },
    ]
  },
  {
    en: 'Phitsanulok', th: 'พิษณุโลก',
    districts: [
      { en: 'Mueang Phitsanulok', th: 'เมืองพิษณุโลก' },
      { en: 'Nakhon Thai', th: 'นครไทย' },
      { en: 'Chat Trakan', th: 'ชาติตระการ' },
      { en: 'Bang Rakam', th: 'บางระกำ' },
      { en: 'Bang Krathum', th: 'บางกระทุ่ม' },
      { en: 'Prom Phiram', th: 'พรหมพิราม' },
      { en: 'Wat Bot', th: 'วัดโบสถ์' },
      { en: 'Wang Thong', th: 'วังทอง' },
      { en: 'Noen Maprang', th: 'เนินมะปราง' },
    ]
  },
  {
    en: 'Phra Nakhon Si Ayutthaya', th: 'พระนครศรีอยุธยา',
    districts: [
      { en: 'Mueang Phra Nakhon Si Ayutthaya', th: 'เมืองพระนครศรีอยุธยา' },
      { en: 'Tha Ruea', th: 'ท่าเรือ' },
      { en: 'Nakhon Luang', th: 'นครหลวง' },
      { en: 'Bang Sai', th: 'บางไทร' },
      { en: 'Bang Ban', th: 'บางบาล' },
      { en: 'Bang Pa-in', th: 'บางปะอิน' },
      { en: 'Bang Pahan', th: 'บางปะหัน' },
      { en: 'Phak Hai', th: 'ผักไห่' },
      { en: 'Phachi', th: 'ภาชี' },
      { en: 'Lat Bua Luang', th: 'ลาดบัวหลวง' },
      { en: 'Wang Noi', th: 'วังน้อย' },
      { en: 'Sena', th: 'เสนา' },
      { en: 'Bang Sai (Sara Buri)', th: 'บางซ้าย' },
      { en: 'Uthai', th: 'อุทัย' },
      { en: 'Maharat', th: 'มหาราช' },
      { en: 'Ban Phraek', th: 'บ้านแพรก' },
    ]
  },
  {
    en: 'Phrae', th: 'แพร่',
    districts: [
      { en: 'Mueang Phrae', th: 'เมืองแพร่' },
      { en: 'Rong Kwang', th: 'ร้องกวาง' },
      { en: 'Long', th: 'ลอง' },
      { en: 'Sung Men', th: 'สูงเม่น' },
      { en: 'Den Chai', th: 'เด่นชัย' },
      { en: 'Song', th: 'สอง' },
      { en: 'Wang Chin', th: 'วังชิ้น' },
      { en: 'Nong Muang Khai', th: 'หนองม่วงไข่' },
    ]
  },
  {
    en: 'Phuket', th: 'ภูเก็ต',
    districts: [
      { en: 'Mueang Phuket', th: 'เมืองภูเก็ต' },
      { en: 'Kathu', th: 'กะทู้' },
      { en: 'Thalang', th: 'ถลาง' },
    ]
  },
  {
    en: 'Prachin Buri', th: 'ปราจีนบุรี',
    districts: [
      { en: 'Mueang Prachin Buri', th: 'เมืองปราจีนบุรี' },
      { en: 'Kabin Buri', th: 'กบินทร์บุรี' },
      { en: 'Na Di', th: 'นาดี' },
      { en: 'Ban Sang', th: 'บ้านสร้าง' },
      { en: 'Prachantakham', th: 'ประจันตคาม' },
      { en: 'Si Maha Phot', th: 'ศรีมหาโพธิ' },
      { en: 'Si Mahosot', th: 'ศรีมโหสถ' },
    ]
  },
  {
    en: 'Prachuap Khiri Khan', th: 'ประจวบคีรีขันธ์',
    districts: [
      { en: 'Mueang Prachuap Khiri Khan', th: 'เมืองประจวบคีรีขันธ์' },
      { en: 'Kui Buri', th: 'กุยบุรี' },
      { en: 'Thap Sakae', th: 'ทับสะแก' },
      { en: 'Bang Saphan', th: 'บางสะพาน' },
      { en: 'Bang Saphan Noi', th: 'บางสะพานน้อย' },
      { en: 'Pran Buri', th: 'ปราณบุรี' },
      { en: 'Hua Hin', th: 'หัวหิน' },
      { en: 'Sam Roi Yot', th: 'สามร้อยยอด' },
    ]
  },
  {
    en: 'Ranong', th: 'ระนอง',
    districts: [
      { en: 'Mueang Ranong', th: 'เมืองระนอง' },
      { en: 'La-un', th: 'ละอุ่น' },
      { en: 'Kapoe', th: 'กะเปอร์' },
      { en: 'Kra Buri', th: 'กระบุรี' },
      { en: 'Suk Samran', th: 'สุขสำราญ' },
    ]
  },
  {
    en: 'Ratchaburi', th: 'ราชบุรี',
    districts: [
      { en: 'Mueang Ratchaburi', th: 'เมืองราชบุรี' },
      { en: 'Chom Bueng', th: 'จอมบึง' },
      { en: 'Suan Phueng', th: 'สวนผึ้ง' },
      { en: 'Damnoen Saduak', th: 'ดำเนินสะดวก' },
      { en: 'Ban Pong', th: 'บ้านโป่ง' },
      { en: 'Bang Phae', th: 'บางแพ' },
      { en: 'Photharam', th: 'โพธาราม' },
      { en: 'Pak Tho', th: 'ปากท่อ' },
      { en: 'Wat Phleng', th: 'วัดเพลง' },
      { en: 'Ban Kha', th: 'บ้านคา' },
    ]
  },
  {
    en: 'Rayong', th: 'ระยอง',
    districts: [
      { en: 'Mueang Rayong', th: 'เมืองระยอง' },
      { en: 'Ban Chang', th: 'บ้านฉาง' },
      { en: 'Klaeng', th: 'แกลง' },
      { en: 'Wang Chan', th: 'วังจันทร์' },
      { en: 'Ban Khai', th: 'บ้านค่าย' },
      { en: 'Pluak Daeng', th: 'ปลวกแดง' },
      { en: 'Khao Chamao', th: 'เขาชะเมา' },
      { en: 'Nikhom Phatthana', th: 'นิคมพัฒนา' },
    ]
  },
  {
    en: 'Roi Et', th: 'ร้อยเอ็ด',
    districts: [
      { en: 'Mueang Roi Et', th: 'เมืองร้อยเอ็ด' },
      { en: 'Kaset Wisai', th: 'เกษตรวิสัย' },
      { en: 'Pathum Rat', th: 'ปทุมรัตต์' },
      { en: 'Chaturaphak Phiman', th: 'จตุรพักตร์พิมาน' },
      { en: 'Thawat Buri', th: 'ธวัชบุรี' },
      { en: 'Phanom Phrai', th: 'พนมไพร' },
      { en: 'Pho Chai', th: 'โพชัย' },
      { en: 'Nong Phok', th: 'หนองพอก' },
      { en: 'Selaphum', th: 'เสลภูมิ' },
      { en: 'Suwannaphum', th: 'สุวรรณภูมิ' },
      { en: 'Mueang Suang', th: 'เมืองสรวง' },
      { en: 'Nong Hi', th: 'หนองฮี' },
      { en: 'At Samat', th: 'อาจสามารถ' },
      { en: 'Moei Wadi', th: 'เมยวดี' },
      { en: 'Si Somdet', th: 'ศรีสมเด็จ' },
      { en: 'Chang Han', th: 'จังหาร' },
      { en: 'Chiang Khwan', th: 'เชียงขวัญ' },
      { en: 'Nong Suea', th: 'หนองเสือ' },
      { en: 'Thung Khao Luang', th: 'ทุ่งเขาหลวง' },
      { en: 'Pho Thong', th: 'โพธิ์ทอง' },
    ]
  },
  {
    en: 'Sa Kaeo', th: 'สระแก้ว',
    districts: [
      { en: 'Mueang Sa Kaeo', th: 'เมืองสระแก้ว' },
      { en: 'Khlong Hat', th: 'คลองหาด' },
      { en: 'Ta Phraya', th: 'ตาพระยา' },
      { en: 'Wang Nam Yen', th: 'วังน้ำเย็น' },
      { en: 'Watthana Nakhon', th: 'วัฒนานคร' },
      { en: 'Aranyaprathet', th: 'อรัญประเทศ' },
      { en: 'Khao Chakan', th: 'เขาฉกรรจ์' },
      { en: 'Khok Sung', th: 'โคกสูง' },
      { en: 'Wang Sombun', th: 'วังสมบูรณ์' },
    ]
  },
  {
    en: 'Sakon Nakhon', th: 'สกลนคร',
    districts: [
      { en: 'Mueang Sakon Nakhon', th: 'เมืองสกลนคร' },
      { en: 'Kusuman', th: 'กุสุมาลย์' },
      { en: 'Kut Bak', th: 'กุดบาก' },
      { en: 'Phanna Nikhom', th: 'พรรณานิคม' },
      { en: 'Phu Phan', th: 'ภูพาน' },
      { en: 'Wanon Niwat', th: 'วานรนิวาส' },
      { en: 'Kham Ta Kla', th: 'คำตากล้า' },
      { en: 'Ban Muang', th: 'บ้านม่วง' },
      { en: 'Akat Amnuai', th: 'อากาศอำนวย' },
      { en: 'Sawang Daen Din', th: 'สว่างแดนดิน' },
      { en: 'Song Dao', th: 'ส่องดาว' },
      { en: 'Tao Ngoi', th: 'เต่างอย' },
      { en: 'Khok Si Suphan', th: 'โคกศรีสุพรรณ' },
      { en: 'Charoen Sin', th: 'เจริญศิลป์' },
      { en: 'Nikhom Nam Un', th: 'นิคมน้ำอูน' },
      { en: 'Waritchaphum', th: 'วาริชภูมิ' },
      { en: 'Phon Na Kaeo', th: 'โพนนาแก้ว' },
      { en: 'Phu Lak', th: 'ภูหลัก' },
    ]
  },
  {
    en: 'Samut Prakan', th: 'สมุทรปราการ',
    districts: [
      { en: 'Mueang Samut Prakan', th: 'เมืองสมุทรปราการ' },
      { en: 'Bang Bo', th: 'บางบ่อ' },
      { en: 'Bang Phli', th: 'บางพลี' },
      { en: 'Phra Pradaeng', th: 'พระประแดง' },
      { en: 'Phra Samut Chedi', th: 'พระสมุทรเจดีย์' },
      { en: 'Bang Sao Thong', th: 'บางเสาธง' },
    ]
  },
  {
    en: 'Samut Sakhon', th: 'สมุทรสาคร',
    districts: [
      { en: 'Mueang Samut Sakhon', th: 'เมืองสมุทรสาคร' },
      { en: 'Krathum Baen', th: 'กระทุ่มแบน' },
      { en: 'Ban Phaeo', th: 'บ้านแพ้ว' },
    ]
  },
  {
    en: 'Samut Songkhram', th: 'สมุทรสงคราม',
    districts: [
      { en: 'Mueang Samut Songkhram', th: 'เมืองสมุทรสงคราม' },
      { en: 'Bang Khonthi', th: 'บางคนที' },
      { en: 'Amphawa', th: 'อัมพวา' },
    ]
  },
  {
    en: 'Saraburi', th: 'สระบุรี',
    districts: [
      { en: 'Mueang Saraburi', th: 'เมืองสระบุรี' },
      { en: 'Kaeng Khoi', th: 'แก่งคอย' },
      { en: 'Nong Khae', th: 'หนองแค' },
      { en: 'Wihan Daeng', th: 'วิหารแดง' },
      { en: 'Nong Saeng', th: 'หนองแซง' },
      { en: 'Ban Mo', th: 'บ้านหมอ' },
      { en: 'Don Phut', th: 'ดอนพุด' },
      { en: 'Nong Don', th: 'หนองโดน' },
      { en: 'Phra Phutthabat', th: 'พระพุทธบาท' },
      { en: 'Sao Hai', th: 'เสาไห้' },
      { en: 'Muak Lek', th: 'มวกเหล็ก' },
      { en: 'Wang Muang', th: 'วังม่วง' },
      { en: 'Chaloem Phra Kiat', th: 'เฉลิมพระเกียรติ' },
    ]
  },
  {
    en: 'Satun', th: 'สตูล',
    districts: [
      { en: 'Mueang Satun', th: 'เมืองสตูล' },
      { en: 'Khuan Don', th: 'ควนโดน' },
      { en: 'Khuan Kalong', th: 'ควนกาหลง' },
      { en: 'Tha Phae', th: 'ท่าแพ' },
      { en: 'La-ngu', th: 'ละงู' },
      { en: 'Thung Wa', th: 'ทุ่งหว้า' },
      { en: 'Manang', th: 'มะนัง' },
    ]
  },
  {
    en: 'Sing Buri', th: 'สิงห์บุรี',
    districts: [
      { en: 'Mueang Sing Buri', th: 'เมืองสิงห์บุรี' },
      { en: 'Bang Rachan', th: 'บางระจัน' },
      { en: 'Khai Bang Rachan', th: 'ค่ายบางระจัน' },
      { en: 'Phrom Buri', th: 'พรหมบุรี' },
      { en: 'Tha Chang', th: 'ท่าช้าง' },
      { en: 'In Buri', th: 'อินทร์บุรี' },
    ]
  },
  {
    en: 'Si Sa Ket', th: 'ศรีสะเกษ',
    districts: [
      { en: 'Mueang Si Sa Ket', th: 'เมืองศรีสะเกษ' },
      { en: 'Yang Chum Noi', th: 'ยางชุมน้อย' },
      { en: 'Kanthararom', th: 'กันทรารมย์' },
      { en: 'Kantharalak', th: 'กันทรลักษ์' },
      { en: 'Khukhan', th: 'ขุขันธ์' },
      { en: 'Phrai Bueng', th: 'ไพรบึง' },
      { en: 'Phu Sing', th: 'ภูสิงห์' },
      { en: 'Rasi Salai', th: 'ราษีไศล' },
      { en: 'Uthumphon Phisai', th: 'อุทุมพรพิสัย' },
      { en: 'Bueng Bun', th: 'บึงบูรพ์' },
      { en: 'Huai Thap Than', th: 'ห้วยทับทัน' },
      { en: 'Non Khun', th: 'โนนคูณ' },
      { en: 'Si Rattana', th: 'ศรีรัตนะ' },
      { en: 'Nam Kliang', th: 'น้ำเกลี้ยง' },
      { en: 'Wang Hin', th: 'วังหิน' },
      { en: 'Phayu', th: 'พยุห์' },
      { en: 'Mueang Chan', th: 'เมืองจันทร์' },
      { en: 'Benchalak', th: 'เบญจลักษ์' },
      { en: 'Prang Ku', th: 'ปรางค์กู่' },
      { en: 'Khun Han', th: 'ขุนหาญ' },
      { en: 'Pho Si Suwan', th: 'โพธิ์ศรีสุวรรณ' },
      { en: 'Sila Lat', th: 'ศิลาลาด' },
    ]
  },
  {
    en: 'Songkhla', th: 'สงขลา',
    districts: [
      { en: 'Mueang Songkhla', th: 'เมืองสงขลา' },
      { en: 'Sathing Phra', th: 'สทิงพระ' },
      { en: 'Chana', th: 'จะนะ' },
      { en: 'Na Thawi', th: 'นาทวี' },
      { en: 'Thepha', th: 'เทพา' },
      { en: 'Saba Yoi', th: 'สะบ้าย้อย' },
      { en: 'Ranot', th: 'ระโนด' },
      { en: 'Krasae Sin', th: 'กระแสสินธุ์' },
      { en: 'Rattaphum', th: 'รัตภูมิ' },
      { en: 'Sadao', th: 'สะเดา' },
      { en: 'Hat Yai', th: 'หาดใหญ่' },
      { en: 'Na Mom', th: 'นาหม่อม' },
      { en: 'Khuan Niang', th: 'ควนเนียง' },
      { en: 'Bang Klam', th: 'บางกล่ำ' },
      { en: 'Singhanakhon', th: 'สิงหนคร' },
      { en: 'Khlong Hoi Khong', th: 'คลองหอยโข่ง' },
    ]
  },
  {
    en: 'Sukhothai', th: 'สุโขทัย',
    districts: [
      { en: 'Mueang Sukhothai', th: 'เมืองสุโขทัย' },
      { en: 'Ban Dan Lan Hoi', th: 'บ้านด่านลานหอย' },
      { en: 'Khiri Mat', th: 'คีรีมาศ' },
      { en: 'Kong Krailat', th: 'กงไกรลาศ' },
      { en: 'Si Satchanalai', th: 'ศรีสัชนาลัย' },
      { en: 'Si Samrong', th: 'ศรีสำโรง' },
      { en: 'Sawankhalok', th: 'สวรรคโลก' },
      { en: 'Si Nakhon', th: 'ศรีนคร' },
      { en: 'Thung Saliam', th: 'ทุ่งเสลี่ยม' },
    ]
  },
  {
    en: 'Suphan Buri', th: 'สุพรรณบุรี',
    districts: [
      { en: 'Mueang Suphan Buri', th: 'เมืองสุพรรณบุรี' },
      { en: 'Bang Pla Ma', th: 'บางปลาม้า' },
      { en: 'Si Prachan', th: 'ศรีประจันต์' },
      { en: 'Dan Chang', th: 'ด่านช้าง' },
      { en: 'Doem Bang Nang Buat', th: 'เดิมบางนางบวช' },
      { en: 'Sam Chuk', th: 'สามชุก' },
      { en: 'Nong Yasai', th: 'หนองหญ้าไซ' },
      { en: 'Song Phi Nong', th: 'สองพี่น้อง' },
      { en: 'U Thong', th: 'อู่ทอง' },
      { en: 'Don Chedi', th: 'ดอนเจดีย์' },
    ]
  },
  {
    en: 'Surat Thani', th: 'สุราษฎร์ธานี',
    districts: [
      { en: 'Mueang Surat Thani', th: 'เมืองสุราษฎร์ธานี' },
      { en: 'Kanchanadit', th: 'กาญจนดิษฐ์' },
      { en: 'Don Sak', th: 'ดอนสัก' },
      { en: 'Ko Samui', th: 'เกาะสมุย' },
      { en: 'Ko Pha-ngan', th: 'เกาะพะงัน' },
      { en: 'Chaiya', th: 'ไชยา' },
      { en: 'Tha Chana', th: 'ท่าชนะ' },
      { en: 'Khiri Rat Nikhom', th: 'คีรีรัฐนิคม' },
      { en: 'Ban Ta Khun', th: 'บ้านตาขุน' },
      { en: 'Phanom', th: 'พนม' },
      { en: 'Tha Chang', th: 'ท่าฉาง' },
      { en: 'Ban Na San', th: 'บ้านนาสาร' },
      { en: 'Ban Na Doem', th: 'บ้านนาเดิม' },
      { en: 'Khian Sa', th: 'เคียนซา' },
      { en: 'Wiang Sa', th: 'เวียงสระ' },
      { en: 'Phrasaeng', th: 'พระแสง' },
      { en: 'Phunphin', th: 'พุนพิน' },
      { en: 'Chai Buri', th: 'ชัยบุรี' },
      { en: 'Vibhavadi', th: 'วิภาวดี' },
    ]
  },
  {
    en: 'Surin', th: 'สุรินทร์',
    districts: [
      { en: 'Mueang Surin', th: 'เมืองสุรินทร์' },
      { en: 'Chumphon Buri', th: 'ชุมพลบุรี' },
      { en: 'Tha Tum', th: 'ท่าตูม' },
      { en: 'Chom Phra', th: 'จอมพระ' },
      { en: 'Prasat', th: 'ปราสาท' },
      { en: 'Kap Choeng', th: 'กาบเชิง' },
      { en: 'Rattanaburi', th: 'รัตนบุรี' },
      { en: 'Sanom', th: 'สนม' },
      { en: 'Sikhoraphum', th: 'ศีขรภูมิ' },
      { en: 'Sangkha', th: 'สังขะ' },
      { en: 'Lamduan', th: 'ลำดวน' },
      { en: 'Samrong Thap', th: 'สำโรงทาบ' },
      { en: 'Buachet', th: 'บัวเชด' },
      { en: 'Phanom Dong Rak', th: 'พนมดงรัก' },
      { en: 'Si Narong', th: 'ศรีณรงค์' },
      { en: 'Khwao Sinarin', th: 'เขวาสินรินทร์' },
      { en: 'Non Narai', th: 'โนนนารายณ์' },
    ]
  },
  {
    en: 'Tak', th: 'ตาก',
    districts: [
      { en: 'Mueang Tak', th: 'เมืองตาก' },
      { en: 'Ban Tak', th: 'บ้านตาก' },
      { en: 'Sam Ngao', th: 'สามเงา' },
      { en: 'Mae Ramat', th: 'แม่ระมาด' },
      { en: 'Tha Song Yang', th: 'ท่าสองยาง' },
      { en: 'Mae Sot', th: 'แม่สอด' },
      { en: 'Phop Phra', th: 'พบพระ' },
      { en: 'Umphang', th: 'อุ้มผาง' },
      { en: 'Wang Chao', th: 'วังเจ้า' },
    ]
  },
  {
    en: 'Trang', th: 'ตรัง',
    districts: [
      { en: 'Mueang Trang', th: 'เมืองตรัง' },
      { en: 'Kantang', th: 'กันตัง' },
      { en: 'Yan Ta Khao', th: 'ย่านตาขาว' },
      { en: 'Palian', th: 'ปะเหลียน' },
      { en: 'Sikao', th: 'สิเกา' },
      { en: 'Huai Yot', th: 'ห้วยยอด' },
      { en: 'Wang Wiset', th: 'วังวิเศษ' },
      { en: 'Na Yong', th: 'นาโยง' },
      { en: 'Ratsada', th: 'รัษฎา' },
      { en: 'Hat Samran', th: 'หาดสำราญ' },
    ]
  },
  {
    en: 'Trat', th: 'ตราด',
    districts: [
      { en: 'Mueang Trat', th: 'เมืองตราด' },
      { en: 'Khlong Yai', th: 'คลองใหญ่' },
      { en: 'Khao Saming', th: 'เขาสมิง' },
      { en: 'Bo Rai', th: 'บ่อไร่' },
      { en: 'Laem Ngop', th: 'แหลมงอบ' },
      { en: 'Ko Kut', th: 'เกาะกูด' },
      { en: 'Ko Chang', th: 'เกาะช้าง' },
    ]
  },
  {
    en: 'Ubon Ratchathani', th: 'อุบลราชธานี',
    districts: [
      { en: 'Mueang Ubon Ratchathani', th: 'เมืองอุบลราชธานี' },
      { en: 'Si Mueang Mai', th: 'ศรีเมืองใหม่' },
      { en: 'Khong Chiam', th: 'โขงเจียม' },
      { en: 'Khemarat', th: 'เขมราฐ' },
      { en: 'Det Udom', th: 'เดชอุดม' },
      { en: 'Na Chaluai', th: 'นาจะหลวย' },
      { en: 'Nam Yuen', th: 'น้ำยืน' },
      { en: 'Buntharik', th: 'บุณฑริก' },
      { en: 'Trakan Phuet Phon', th: 'ตระการพืชผล' },
      { en: 'Kut Khaopun', th: 'กุดข้าวปุ้น' },
      { en: 'Muang Sam Sip', th: 'ม่วงสามสิบ' },
      { en: 'Warin Chamrap', th: 'วารินชำราบ' },
      { en: 'Phibun Mangsahan', th: 'พิบูลมังสาหาร' },
      { en: 'Tan Sum', th: 'ตาลสุม' },
      { en: 'Pho Sai', th: 'โพธิ์ไทร' },
      { en: 'Samrong', th: 'สำโรง' },
      { en: 'Don Mot Daeng', th: 'ดอนมดแดง' },
      { en: 'Sirindhorn', th: 'สิรินธร' },
      { en: 'Thung Si Udom', th: 'ทุ่งศรีอุดม' },
      { en: 'Na Yia', th: 'นาเยีย' },
      { en: 'Na Tan', th: 'นาตาล' },
      { en: 'Lao Suea Kok', th: 'เหล่าเสือโก้ก' },
      { en: 'Sawang Wirawong', th: 'สว่างวีระวงศ์' },
      { en: 'Nam Khun', th: 'น้ำขุ่น' },
    ]
  },
  {
    en: 'Udon Thani', th: 'อุดรธานี',
    districts: [
      { en: 'Mueang Udon Thani', th: 'เมืองอุดรธานี' },
      { en: 'Kut Chap', th: 'กุดจับ' },
      { en: 'Nong Wua So', th: 'หนองวัวซอ' },
      { en: 'Kumphawapi', th: 'กุมภวาปี' },
      { en: 'Non Sa-at', th: 'โนนสะอาด' },
      { en: 'Nong Han', th: 'หนองหาน' },
      { en: 'Thung Fon', th: 'ทุ่งฝน' },
      { en: 'Chai Wan', th: 'ไชยวาน' },
      { en: 'Si That', th: 'ศรีธาตุ' },
      { en: 'Wang Sam Mo', th: 'วังสามหมอ' },
      { en: 'Ban Dung', th: 'บ้านดุง' },
      { en: 'Ban Phue', th: 'บ้านผือ' },
      { en: 'Nam Som', th: 'น้ำโสม' },
      { en: 'Phen', th: 'เพ็ญ' },
      { en: 'Sang Khom', th: 'สร้างคอม' },
      { en: 'Nong Saeng', th: 'หนองแสง' },
      { en: 'Na Yung', th: 'นายูง' },
      { en: 'Phibun Rak', th: 'พิบูลย์รักษ์' },
      { en: 'Ku Kaeo', th: 'กู่แก้ว' },
      { en: 'Prachak Sinlapakhom', th: 'ประจักษ์ศิลปาคม' },
    ]
  },
  {
    en: 'Uthai Thani', th: 'อุทัยธานี',
    districts: [
      { en: 'Mueang Uthai Thani', th: 'เมืองอุทัยธานี' },
      { en: 'Thap Than', th: 'ทัพทัน' },
      { en: 'Sawang Arom', th: 'สว่างอารมณ์' },
      { en: 'Nong Chang', th: 'หนองฉาง' },
      { en: 'Nong Kha Yang', th: 'หนองขาหย่าง' },
      { en: 'Ban Rai', th: 'บ้านไร่' },
      { en: 'Lan Sak', th: 'ลานสัก' },
      { en: 'Huai Khot', th: 'ห้วยคต' },
    ]
  },
  {
    en: 'Uttaradit', th: 'อุตรดิตถ์',
    districts: [
      { en: 'Mueang Uttaradit', th: 'เมืองอุตรดิตถ์' },
      { en: 'Tron', th: 'ตรอน' },
      { en: 'Tha Pla', th: 'ท่าปลา' },
      { en: 'Nam Pat', th: 'น้ำปาด' },
      { en: 'Fak Tha', th: 'ฟากท่า' },
      { en: 'Ban Khok', th: 'บ้านโคก' },
      { en: 'Phichai', th: 'พิชัย' },
      { en: 'Laplae', th: 'ลับแล' },
      { en: 'Thong Saen Khan', th: 'ทองแสนขัน' },
    ]
  },
  {
    en: 'Yala', th: 'ยะลา',
    districts: [
      { en: 'Mueang Yala', th: 'เมืองยะลา' },
      { en: 'Betong', th: 'เบตง' },
      { en: 'Bannang Sata', th: 'บันนังสตา' },
      { en: 'Than To', th: 'ธารโต' },
      { en: 'Yaha', th: 'ยะหา' },
      { en: 'Raman', th: 'รามัน' },
      { en: 'Kabang', th: 'กาบัง' },
      { en: 'Krong Pinang', th: 'กรงปินัง' },
    ]
  },
  {
    en: 'Yasothon', th: 'ยโสธร',
    districts: [
      { en: 'Mueang Yasothon', th: 'เมืองยโสธร' },
      { en: 'Sai Mun', th: 'ทรายมูล' },
      { en: 'Kut Chum', th: 'กุดชุม' },
      { en: 'Kham Khuean Kaeo', th: 'คำเขื่อนแก้ว' },
      { en: 'Pa Tio', th: 'ป่าติ้ว' },
      { en: 'Maha Chana Chai', th: 'มหาชนะชัย' },
      { en: 'Kho Wang', th: 'ค้อวัง' },
      { en: 'Loeng Nok Tha', th: 'เลิงนกทา' },
      { en: 'Thai Charoen', th: 'ไทยเจริญ' },
    ]
  },
];

// Helper to get province names based on language
export function getProvinceNames(lang = 'en') {
  return THAILAND_PROVINCES.map(p => lang === 'th' ? p.th : p.en).sort((a, b) => a.localeCompare(b, lang === 'th' ? 'th' : 'en'));
}

// Helper to get district names for a given province
export function getDistrictNames(provinceName, lang = 'en') {
  const province = THAILAND_PROVINCES.find(p =>
    p.en.toLowerCase() === provinceName.toLowerCase() ||
    p.th === provinceName
  );
  if (!province) return [];
  return province.districts.map(d => lang === 'th' ? d.th : d.en).sort((a, b) => a.localeCompare(b, lang === 'th' ? 'th' : 'en'));
}
